version: '3.8'

services:
  api1:
    image: 'mariacavalc/javinha_rinha_backend:latest'
    hostname: api1
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.325'
          memory: '0.5GB'
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=public
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  api2:
    image: 'mariacavalc/javinha_rinha_backend:latest'
    hostname: api2
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.325'
          memory: '0.5GB'
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=public
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  postgres:
    user: postgres
    image: 'postgres:latest'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_backend
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

