version: '3'

services:
  postgres:
    user: postgres
    image: 'postgres:latest'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_backend

  app:
    image: 'mariacavalc/javinha_rinha_backend:latest'
    restart: always
    container_name: app
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/rinha_backend
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - postgres
