version: '3'

services:
  db:
    image: 'postgres:14.1-alpine'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: rinha_backend
    ports:
      - "5432:5432"
