spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rinha_backend?createDatabaseIfNotExist=true
    username: root
    password: r00t
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create