spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha_backend
    username: user
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      hbm2ddl:
        auto: update